name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      if: hashFiles('package.json') != ''
      run: npm ci
    - name: Run tests
      if: hashFiles('package.json') != ''
      run: npm test --if-present
